# Package Build Configuration
name: PCK.AUTOMIC_OPENSTACK

appdata: ae/APPDATA
source: ae/content

# binary object resource mapping will be defined here
# please add resources here
binaries:
  - object: RESOURCES/LIBS/PCK.AUTOMIC_OPENSTACK.PRV.STORE
    resources:
      - name: OPENSTACK 
        type: BINARY
        path: tools/target/openstack-tool.jar
        version: 1.0.0